name: Check CloudFormation Templates with CFN Guard

on: 
  pull_request:
    branches:
      - main
    types: [opened, synchronize, reopened]

jobs:
  guard:
    runs-on: ubuntu-latest
    name: CloudFormation Guard validate
    permissions:
      # only required when create-review is true
      pull-requests: write
      # only required for workflows in private repositories
      contents: read
    steps: 
      - name: checkout repository
        uses: actions/checkout@v4
        
      - name: cfn-lint-action
        uses: ScottBrenner/cfn-lint-action@v2.4.6
      - name: Print the Cloud Formation Linter Version & run Linter.
        run: |
          shopt -s globstar # enable globbing
          cfn-lint --version
          cfn-lint -t ./*.json

            
