name: Check CloudFormation Templates with CFN Guard

on: 
  pull_request:
    branches:
      - main
    types: [opened, synchronize, reopened]

jobs:
  aws-guard-rules-registry-integration-tests-linux-and-macos:
    runs-on: ubuntu-latest
    name: Integration tests against aws-guard-rules-registry
    steps:
      - uses: actions/checkout@v3
        name: Checkout cfn-guard
        with:
          repository: aws-cloudformation/cloudformation-guard
          path: cloudformation-guard
      - name: Build binary
        shell: bash
        run: |
          cd cloudformation-guard/guard/
          cargo build --release
          ls -lrht ../target/release/
      - name: Generate rule using cfn-guard rungen
        run: |
            ls -lrth
            cloudformation-guard/target/release/cfn-guard rulegen --template ./dashboard.json
          
          
