name: Check CloudFormation Templates with CFN Guard

on: 
  pull_request:
    branches:
      - main
    types: [opened, synchronize, reopened]

jobs:
  guard:
    runs-on: ubuntu-latest
    name: CloudFormation Guard validate
    steps: 
      - name: CloudFormation Guard validate
        uses: aws-cloudformation/cloudformation-guard@action-v0.0.5
        with:
          rules: '.'
          data: '.'
          run: |
            ls -lrht
