name: Check CloudFormation Templates with CFN Guard

on: 
  pull_request:
    branches:
      - main
    types: [opened]

jobs:
  aws-guard-rules-registry-integration-tests-linux-and-macos:
    strategy:
      matrix:
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    name: Integration tests against aws-guard-rules-registry
    steps:
      - uses: actions/checkout@v3
        name: Checkout cfn-guard
        with:
          repository: aws-cloudformation/cloudformation-guard
          path: cloudformation-guard
      - name: Build binary
        run: |
          cd cloudformation-guard/guard/
          cargo build --release
      - uses: actions/checkout@v3
        name: Checkout aws-guard-rules-registry
        with:
          repository: aws-cloudformation/aws-guard-rules-registry
          path: aws-guard-rules-registry
          ref: main
      - name: Run test
        run: |
          ls -lrht
