name: Check if logical id naming convention is compliant or not

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    types: [opened,synchronize,reopened]

jobs:
  run-python-code:
    runs-on: ubuntu-latest

    steps:
      # Checkout your repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9' # Replace with your desired Python version, e.g., '3.8'

      # Install dependencies
      - name: Install YAML module
        run: pip3 install pyyaml

      # Run your Python script
      - name: Run Python Code
        run: |
          echo "Running Python script..."
          python3 compliant_logicalid.py > output.log
          echo "Script finished!" 

      - name: Generate Summary
        run: |
          echo "# Workflow Summary" >> $GITHUB_STEP_SUMMARY
          echo "## Python Code Execution" >> $GITHUB_STEP_SUMMARY
          echo "The Python script has been executed successfully." >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "### Output from the script:" >> $GITHUB_STEP_SUMMARY
          echo '```' >> $GITHUB_STEP_SUMMARY
          cat output.log >> $GITHUB_STEP_SUMMARY
          echo '```' >> $GITHUB_STEP_SUMMARY
